package My::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'My::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbix_schema_test',
        user => 'dbix_schema_test',
        password => 'TfAwVGr!j5',
        AutoCommit => q{1},
    }
);

=head1 NAME

My::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<My>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<My::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
